apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vite-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DPEDITS/DEVOPS.git # <--- IMPORTANT: Replace with YOUR GitHub repo URL!
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true