apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: default
type: Opaque
data:
  username: bXl1c2VybmFtZQ== # base64 encoded "myusername"
  password: c2VjcmV0cGFzc3dvcmQ= # base64 encoded "secretpassword"