apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        image: 194644528937.dkr.ecr.us-east-1.amazonaws.com/my-vite-app:eeb169cae44623f8c56a794116d51a90cebee5ab
        ports:
        - containerPort: 80
