apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
      - name: vite-app
        # This image tag will be replaced by the GitHub Actions pipeline
        image: 194644528937.dkr.ecr.us-east-1.amazonaws.com/my-vite-app:992bf07122c09a7f882ade519804be08f852396d
        ports:
        - containerPort: 80  