---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    API_KEY: AgC9j1r+RQdoM/+CH3C181YmGDTIyUH21WORBtiW77H0crapP/Tz0ev00Ed7K8AI3HMikDxo/hj15XKh1aOGtATmoolZzz3ZezYhFXM9PSZGDYhCtKH7fYPkwn0kiI9ZV4ONFr6QOAzuBhwK1D2dyDECTKqI1MXOSSDF8eCQWAuigJsN04q06ch7p8Sn6SlOVVD0l2owZGOo9r3OmdZ71nsR9mKr67o5m/hwG08SmqDPo0HCMwg47T13YFSrjMwr+Hjff6NJQQCDAr+brAyEMMNj4tUi20Hk2i1nzZqNT/H0Dw3Y5iwlFLxQbvm0mGI4RBlqo8gjVs2Qi9A5zq7umnwmZoSKpKIEjRAYulendsujcJqs26irh2v4/5TTA/GutM5SROnwjJEVZEob1uTYPidkJA91BLSItFSVZmZsWELkyhKtqeFtFTCN58KBhu9Uy0S5yZvGWAVUjLwmHQ3JTk/TpCWhMReixSmwpQRyEi1UfzPXjjbspDMu+TKu3IfSj5p8qB3t2mywQxNj3XrKovI40HcVa8HXd0WEbaa9zDbIgd+vFO8QUt37yOeoWfDb/J4KXMqF1uzjmwNMqjjGNfnU07GAQU+OTTRj7r1+05VK/zXa2cMIpBvntoD0ZW0s0Ws01Q7uuWmgLgDNJd+8WxgjKz5n6tyNDobgtIGZJo8YOphcWslMhYNqRV9tBxoDF2+qTplpTANm3a9D1D/O6Jx+1A==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
